---

- name: "Install & Instantiate Jenkins Templates"
  hosts: openshift

  vars_prompt:
    - name: "openshift_user"
      prompt: "user to login into OpenShift"
    - name: "openshift_password"
      prompt: "password for previous OpenShift user"
    - name: "openshift_url"
      prompt: "OpenShift REST API endpoint"

  pre_tasks:

  - include_vars:
      file: jenkins.json

  # this is done in create-openshift-resources, maybe there is a more elegant way to handle this long term?
  - name: 'Login to OC'
    command: >
      oc login {{ openshift_url }} -u {{ openshift_user }} -p {{ openshift_password }}

    # TODO we need to move this function to an ansible module
  - name: 'Create OpenShift Project'
    command: >
      oc new-project security-symposium-ci
    ignore_errors: yes

  - name: 'Install Jenkins S2I Template'
    command: >
      oc create -f jenkins-s2i-template.json -n security-symposium-ci
    ignore_errors: yes

  roles:
    - openshift-defaults
    - create-openshift-resources